// Copyright (c) 2026 Michael Wroblewski / ShivaCore / A-TownChain-Okosystems. All Rights Reserved.
import { Globe, FileText, Component, MonitorIcon, Presentation, Palette, PlaySquare, Music, Video, Image, Database, Users, MessageSquare, Calculator, Calendar, Clock, Sword } from 'lucide-react';
import { GateToHellBrowser } from './components/GateToHellBrowser.tsx';
import { OfficeSuiteView } from './components/OfficeSuiteView.tsx';
import { ATCWordView, ATCExcelView, ATCPowerPointView } from './components/OfficeApps.tsx';
import { ATCDjStudioView } from './components/ATCDjStudioView.tsx';
import { CalculatorView } from './components/CalculatorView.tsx';
import { NotepadView } from './components/NotepadView.tsx';
import { CalendarView } from './components/CalendarView.tsx';
import { ClockView } from './components/ClockView.tsx';
import { Paint3DView } from './components/Paint3DView.tsx';
import { ATCAudioPlayerView, ATCVideoPlayerView, ATCImageViewerView, ATCMediaPlayerHub } from './components/MediaApps.tsx';
import { SocialMediaView } from './components/SocialMediaView.tsx';
import { P2PChatView } from './components/P2PChatView.tsx';
import { BattleArenaView } from './components/BattleArenaView.tsx';
import { ATCAssetView } from './components/ATCAssetView.tsx';
import { FranchiseFactoryView } from './components/FranchiseFactoryView.tsx';
import { ATownTestView } from './components/ATownTestView.tsx';

export const MARKETPLACE_EXTRA_APPS = [
  {
    id: "atown_browser",
    name: "GateToHell Browser",
    component: GateToHellBrowser,
    icon: Globe,
    category: "Media & Web",
    price: "Free",
    numPrice: 0,
    author: "ATC Core Team",
    rating: "4.9",
    downloads: "2.5M",
  },
  {
    id: "office_suite",
    name: "A-Town Office Suite",
    component: OfficeSuiteView,
    icon: FileText,
    category: "Productivity",
    price: "Premium",
    numPrice: 20,
    author: "ATC Productivity",
    rating: "4.8",
    downloads: "1.2M",
  },
  {
    id: "atc_word",
    name: "A-TownChain Word",
    component: ATCWordView,
    icon: FileText,
    category: "Productivity",
    price: "Free",
    numPrice: 0,
    author: "ATC Productivity",
    rating: "4.7",
    downloads: "800k",
  },
  {
    id: "atc_excel",
    name: "A-TownChain Excel",
    component: ATCExcelView,
    icon: MonitorIcon,
    category: "Productivity",
    price: "Free",
    numPrice: 0,
    author: "ATC Productivity",
    rating: "4.8",
    downloads: "750k",
  },
  {
    id: "atc_present",
    name: "A-TownChain Present",
    component: ATCPowerPointView,
    icon: Presentation,
    category: "Productivity",
    price: "Free",
    numPrice: 0,
    author: "ATC Productivity",
    rating: "4.6",
    downloads: "600k",
  },
  {
    id: "atc_paint",
    name: "dPaint 3D Mesh",
    component: Paint3DView,
    icon: Palette,
    category: "Design",
    price: "Free",
    numPrice: 0,
    author: "ATC Creative",
    rating: "4.9",
    downloads: "1.5M",
  },
  {
    id: "atc_dj_studio",
    name: "ATC-DjStudio",
    component: ATCDjStudioView,
    icon: Music,
    category: "Media & Web",
    price: "Free",
    numPrice: 0,
    author: "ATC Audio Labs",
    rating: "4.8",
    downloads: "450k",
  },
  {
    id: "atc_media_hub",
    name: "ATC-Mediaplayer",
    component: ATCMediaPlayerHub,
    icon: PlaySquare,
    category: "Media & Web",
    price: "Free",
    numPrice: 0,
    author: "ATC Media",
    rating: "4.7",
    downloads: "2.1M",
  },
  {
    id: "atc_audio",
    name: "ATC-Audio Player",
    component: ATCAudioPlayerView,
    icon: Music,
    category: "Media & Web",
    price: "Free",
    numPrice: 0,
    author: "ATC Media",
    rating: "4.6",
    downloads: "1M",
  },
  {
    id: "atc_video",
    name: "ATC-Video Player",
    component: ATCVideoPlayerView,
    icon: Video,
    category: "Media & Web",
    price: "Free",
    numPrice: 0,
    author: "ATC Media",
    rating: "4.5",
    downloads: "1.2M",
  },
  {
    id: "atc_bilder",
    name: "ATC-Bilder",
    component: ATCImageViewerView,
    icon: Image,
    category: "Media & Web",
    price: "Free",
    numPrice: 0,
    author: "ATC Media",
    rating: "4.6",
    downloads: "1.5M",
  },
  {
    id: "ATCAsset",
    name: "ATCAsset Store",
    component: ATCAssetView,
    icon: Database,
    category: "Gaming",
    price: "Free",
    numPrice: 0,
    author: "ATC Gaming",
    rating: "4.8",
    downloads: "800k",
  },
  {
    id: "battle_arena",
    name: "Battle Arena",
    component: BattleArenaView,
    icon: Sword,
    category: "Gaming",
    price: "Free",
    numPrice: 0,
    author: "ATC Gaming Labs",
    rating: "4.9",
    downloads: "3M!",
  },
  {
    id: "social_app",
    name: "ATC-Sozialmedia",
    component: SocialMediaView,
    icon: Users,
    category: "Social Network",
    price: "Free",
    numPrice: 0,
    author: "ATC Connect",
    rating: "4.7",
    downloads: "5M+",
  },
  {
    id: "p2p_chat",
    name: "P2P Chat",
    component: P2PChatView,
    icon: MessageSquare,
    category: "Social Network",
    price: "Free",
    numPrice: 0,
    author: "ATC Privacy Labs",
    rating: "4.9",
    downloads: "2.8M",
  },
  {
    id: "franchise_factory",
    name: "Franchise Factory",
    component: FranchiseFactoryView,
    icon: Component,
    category: "AI Publishing",
    price: "Free",
    numPrice: 0,
    author: "ATC Publishing",
    rating: "4.9",
    downloads: "400k",
  },
  {
    id: "calculator",
    name: "ATC-Calculator",
    component: CalculatorView,
    icon: Calculator,
    category: "Utilities",
    price: "Free",
    numPrice: 0,
    author: "ATC System",
    rating: "4.5",
    downloads: "1M+",
  },
  {
    id: "notepad",
    name: "Notepad",
    component: NotepadView,
    icon: FileText,
    category: "Utilities",
    price: "Free",
    numPrice: 0,
    author: "ATC System",
    rating: "4.6",
    downloads: "1.2M",
  },
  {
    id: "calendar",
    name: "Calendar",
    component: CalendarView,
    icon: Calendar,
    category: "Utilities",
    price: "Free",
    numPrice: 0,
    author: "ATC System",
    rating: "4.4",
    downloads: "800k",
  },
  {
    id: "clock",
    name: "System Clock",
    component: ClockView,
    icon: Clock,
    category: "Utilities",
    price: "Free",
    numPrice: 0,
    author: "ATC System",
    rating: "4.5",
    downloads: "900k",
  },
  {
    id: "atown_test",
    name: "A-Town Test Suite",
    component: ATownTestView,
    icon: Component,
    category: "Developer Tools",
    price: "Free",
    numPrice: 0,
    author: "ATC Dev",
    rating: "4.8",
    downloads: "200k",
  }
];
